version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ecom-api
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: development
      APP_NAME: ecom-backend
      HOST: 0.0.0.0
      PORT: 3000
      LOG_LEVEL: info
      JWT_SECRET: super-secret-change-me
      JWT_EXPIRES_IN: 1h
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432
      POSTGRES_DB: ecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
    restart: unless-stopped