services:
  postgres_test:
    image: postgres:16-alpine
    container_name: ecom-postgres-test
    environment:
      POSTGRES_DB: ecom_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecom_test"]
      interval: 3s
      timeout: 3s
      retries: 20

  redis_test:
    image: redis:7-alpine
    container_name: ecom-redis-test
    ports:
      - "56379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20
