version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ecom-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      APP_NAME: ecom-backend
      HOST: 0.0.0.0
      PORT: 3000
      LOG_LEVEL: info
      JWT_SECRET: super-secret-change-me
      JWT_EXPIRES_IN: 1h
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: ecom-postgres
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ecom-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
